server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rusakovich-viktar/micro-config-server-cloud.git
          default-label: develop
          search-paths: "{application}"














